password = []
size = [
    0,
    0,
    0,
    0,
]
size_ft = [
    0,
    0,
    0,
    0,
]
size_pf = [
    0,
    0,
    0,
    0,
]
view_style = 'original'
scroll_style = 'scrollauto'
edge_scroll_edge_thickness = 100
image_quality = 'balanced'
custom_image_quality = [50]
show_remote_cursor = false
lock_after_session_end = false
terminal-persistent = false
privacy_mode = false
allow_swap_key = false
port_forwards = []
direct_failures = 0
disable_audio = false
disable_clipboard = false
enable-file-copy-paste = true
show_quality_monitor = false
follow_remote_cursor = false
follow_remote_window = false
keyboard_mode = 'map'
view_only = false
show_my_cursor = false
sync-init-clipboard = false
trackpad-speed = 100

[options]
custom-fps = '30'
i444 = ''
zoom-cursor = ''
codec-preference = 'auto'
swap-left-right-mouse = ''
collapse_toolbar = 'Y'

[ui_flutter]
wm_RemoteDesktop = '{"width":640.0,"height":1062.0,"offsetWidth":1280.0,"offsetHeight":0.0,"isMaximized":false,"isFullscreen":false}'

[info]
username = 'linus.nilsson10'
hostname = '1h85192kz1'
platform = 'Windows'

[transfer]
write_jobs = []
read_jobs = []
