enc_id = '0023Kpz+2VosiO3oRoGtHaJBYSzywbHiR0NA=='
password = ''
salt = ''
key_pair = [
    [
    117,
    137,
    143,
    173,
    170,
    120,
    127,
    132,
    112,
    11,
    160,
    37,
    60,
    28,
    186,
    6,
    135,
    158,
    126,
    16,
    98,
    233,
    113,
    96,
    129,
    107,
    140,
    4,
    139,
    87,
    224,
    118,
    62,
    119,
    43,
    23,
    184,
    93,
    154,
    152,
    217,
    51,
    170,
    49,
    196,
    9,
    214,
    139,
    71,
    238,
    72,
    194,
    113,
    45,
    172,
    116,
    159,
    96,
    84,
    0,
    13,
    69,
    133,
    231,
],
    [
    62,
    119,
    43,
    23,
    184,
    93,
    154,
    152,
    217,
    51,
    170,
    49,
    196,
    9,
    214,
    139,
    71,
    238,
    72,
    194,
    113,
    45,
    172,
    116,
    159,
    96,
    84,
    0,
    13,
    69,
    133,
    231,
],
]
key_confirmed = true

[keys_confirmed]
rs-ny = true
