remote_id = '223275796'
kb_layout_type = ''
size = [
    0,
    0,
    0,
    0,
]
fav = []

[options]
remote-menubar-drag-right = '1.0'
remote-menubar-drag-left = '0.0'

[ui_flutter]
wm_RemoteDesktop = '{"width":480.0,"height":1062.0,"offsetWidth":960.0,"offsetHeight":0.0,"isMaximized":false,"isFullscreen":false}'
peer-tab-index = '0'
peer-sorting = 'Remote ID'
wm_ViewCamera = '{"width":640.0,"height":1062.0,"offsetWidth":1280.0,"offsetHeight":0.0,"isMaximized":false,"isFullscreen":false}'
